@baseUrl = http://localhost:1337/api/v1


### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Ruta protegida
GET http://localhost:1337/health
Authorization: Bearer {{loginRequest.response.body.token}}


### Chat con la IA
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Cuáles son las mejores criptomonedas para invertir a largo plazo?"
}


### Chat con mercado tradicional
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Cómo están las principales acciones del mercado hoy?"
}


### Pregunta fuera de tema
POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
    "message": "¿Quién ganó el mundial 2022?"
}


